#ifndef _CONTROL_PACKET_H_
#define _CONTROL_PACKET_H_

#define HEADER_BYTE_SIZE 8
#define LENGTH_PREFIX_BYTE_POS 6
#define NUM_BYTES_LENGTH_PREFIX 2
#define CONTROL_CODE_BYTE_POS 4
#define NUM_BYTES_CONTROL_CODE 1

#endif